### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by ezmiller** [Kapeli/cheatsheets#189]
It's unclear from the Readme what these cheat sheets are in fact. Can they be downloaded into Dash? If so, how?

**Comment by Kapeli** [comment]
They can be downloaded in Dash in Preferences > Downloads > Cheat Sheets.

**Comment by ezmiller** [comment]
Thanks! Maybe a line about that in the Readme?

**Comment by Kapeli** [comment]
Done.
