### ISSUE TITLE
IPython >> Jupyter + Improvements

### ISSUE THREAD

**Issue by jaypeedevlin** [Kapeli/cheatsheets#242]
I'm considering contributing a PR with improvements to this cheatsheat - would you be open to this?.  Additionally, IPython notebook has been called Jupyter notebook since 2014, would there be any issues from your end if I changed the name at the same time??

**Comment by Kapeli** [comment]
Sure, go ahead.

I have no issue with the cheat sheet being renamed, but please note that Dash will treat the cheat sheet as a new one and old users won't get updated to the cheat sheet with the new name.
