### ISSUE TITLE
Please remove copied YAML content

### ISSUE THREAD

**Issue by lwindolf** [Kapeli/cheatsheets#378]
Hello,

you copied a rather large section of content from https://lzone.de/cheat-sheet/YAML to https://kapeli.com/cheat_sheets/YAML.docset/Contents/Resources/Documents/index. I know there is a backlink, but I do not think it's fine to just copy (without asking) from another page on the same Google key word on rank 2. Especially if you are doing this professionally.

So I'm asking for this content to be removed.

Best Regards

**Comment by Kapeli** [comment]
I've removed the copied content.

@mvdwoord: you're the original creator of the cheat sheet. If you'd like to update it with new examples, please submit a pull request.

**Comment by mvdwoord** [comment]
@lwindolf Understand. Did not check at that time, think I just found it a useful resource.
I have no need for an offline YAML cheatsheet/docs for some time now, so no interest in creating any replacement.
Thanks for letting me know though.

**Comment by lwindolf** [comment]
@Kapeli Thank you!
