### ISSUE TITLE
Improvement on git stash push

### ISSUE THREAD

**Issue by TheGooner93** [Kapeli/cheatsheets#387]
Problem:
As per the [ohmyzsh README for git](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git), `git stash push` and `git stash save` commands are mapped to the same alias `gsta`
Also the Kapeli cheatsheet shows the above mapping only to `git stash save`

Potential fix:
Ideally we would need to update the mapping in the Kapeli cheatsheet for `gsta` -> `git stash push` or add a separate one as per the ohmyzsh documentation(displayed above).
Even the [git documentation](https://git-scm.com/docs/git-stash#Documentation/git-stash.txt-save-p--patch-k--no-keep-index-u--include-untracked-a--all-q--quietltmessagegt) mentions that `git stash save` is now a deprecated command.

**Comment by TheGooner93** [comment]
I would like to work on this if possible

**Comment by Kapeli** [comment]
> I would like to work on this if possible

Sure. Please submit a pull request for this when you can.
