### ISSUE TITLE
How to contribute a non-ruby cheatsheet?

### ISSUE THREAD

**Issue by holyjak** [Kapeli/cheatsheets#402]
I have a AsciiDoctor cheatsheet, which is essentially a HTML with an icon, wrapped in the docset format - see https://github.com/holyjak/dash-asciidoc-cheatsheet/releases How do I contribute it here? Thanks!

**Comment by holyjak** [comment]
Perhaps you could accept DocSet.html instead of DocSet.rb?

But there is still one problem: My docset has, in addition to Categories and Entries, also indexed "commands" so that when you search for "macro" you will be brought to the [Extra](https://github.com/holyjak/dash-asciidoc-cheatsheet/blob/main/web-cheatsheet.adoc#extra-1) entry that contains it. This is very valuable IMHO, though you could argue that people could also just search in the page text....

**Comment by Kapeli** [comment]
What `cheatset` limitations stopped you from converting this cheat sheet to the regular format? `notes` support HTML alongside Markdown as far as I know.

Have you considered instead of generating HTML that looks like a Dash cheat sheet you could generate a cheat sheet in the regular format instead?

**Comment by holyjak** [comment]
Two things. Generating Ruby code is more pain than generating HTML, but I could overcome that. The other is:

> My docset has, in addition to Categories and Entries, also indexed "commands" so that when you search for "macro" you will be brought to the Extra entry that contains it. This is very valuable IMHO, though you could argue that people could also just search in the page text....

**Comment by Kapeli** [comment]
That's something standard cheat sheets support too. You can add Commands to the index using `command` in the cheat sheet - https://github.com/Kapeli/cheatset#usage.

Is this not suitable for your needs?

**Comment by holyjak** [comment]
Ah, now I remember. The main problem is that cheatset tries to interpret the content of my html as markdown so if I use something like ` inside it, it will screw it up.

**Comment by Kapeli** [comment]
You can escape those using backslash `\`

**Comment by holyjak** [comment]
Yes, but going through all my HTML to escape everything that Markdown might try to interpret is insanity. I do not know Markdown's behavior to be 100% sure where the escapes are necessary and where they would just be preserved in the output, which is also undesirable. I guess it is not as simple as escaping every `*`, `_`, backtick. Couldn't it just follow the markdown specification and not intepret markdown inside block html elements? Or at least have a switch to turn this off / on?

**Comment by Kapeli** [comment]
> Couldn't it just follow the markdown specification and not intepret markdown inside block html elements? Or at least have a switch to turn this off / on?

Can you open a separate issue regarding this with a sample cheat sheet where this occurs and I'll look into it?

**Comment by holyjak** [comment]
I can attach a sample cheat sheet to Kapeli/cheatset#36 ?

**Comment by holyjak** [comment]
Fixed when  Kapeli/cheatset#36 was fixed by adding support for `html_notes`
